### ISSUE TITLE
kristforge says it mined about double what it actually did

### ISSUE THREAD

**Issue by psmpm** [tmpim/kristforge#16] opened 2021-05-27 11:50 UTC
So before I ran kristforge, I had 131 kst. But then, when I ran kristforge until it said "mined 100 kst", i had only gotten to 181 kst, half of what kristforge said. I believe this may be an issue with it not knowing what the actual block value is, but I haven't looked at the source code so I don't really know. Here's the command I used:
`kristforge.exe mine --no-cpu <my address>`

**Comment by Lemmmy** [comment] 2021-05-27 11:53
> I believe this may be an issue with it not knowing what the actual block value is

The block value hasn't been more than 1 KST for the last 11 days, though:
![image](https://user-images.githubusercontent.com/858456/119821582-a4b6cc00-beea-11eb-9c18-5097c87832af.png)

Does KristForge say it mines 2 KST each time you get a block?

**Comment by Lemmmy** [comment] 2021-05-27 18:27
thats amazing

**Comment by dmarcuse** [comment] 2021-05-27 18:27
This seems to have been caused by https://github.com/tmpim/Krist/pull/57, which affected how kristforge handled incoming server messages. I've pushed a fix and will be publishing a new release for it shortly.

**Closed as completed** 2021-05-27 18:26 UTC

**Comment by dmarcuse** [comment] 2021-05-27 18:38
[Done!](https://github.com/tmpim/kristforge/releases/tag/v3.1.5)
